### ISSUE TITLE
java documentation for face recognition

### ISSUE THREAD

**Issue by kishoreaoe** [regulaforensics/FaceSDK-web-java-client#11]
Dear Team,
could you please let us know where can we find the Java documentation for Face Recognition comparison.

**Comment by hleb-albau** [comment]
Hello, kishoreaoe,

currently, all we have are one example [example](https://github.com/regulaforensics/FaceSDK-web-java-client/blob/master/example/src/main/java/com/regula/facesdk/webclient/Main.java) and [model definitions](https://github.com/regulaforensics/FaceSDK-web-openapi/blob/master/matching.yml).



Also, you can find mobile sdk documentation [here](https://docs.regulaforensics.com/home/)

**Comment by kishoreaoe** [comment]
Thanks alot, @hleb-albau for the quick reply, 

Have tried the "Example" given above, after framing the entire request and when hit, we are getting "Method Not Allowed".
Could you please guide us on this. We have bought the license and we are working to integrate the same with web-sdk via java component.

**Comment by hleb-albau** [comment]
Ah, I see. 
We updated our client and example for future release 3.0.0. As far I understand you use an older version of the faces web server.
Here you have two options - use our nightly 3.0.0 build, which we plan to release soon. Or use an older client with [older example](https://github.com/regulaforensics/FaceSDK-web-java-client/blob/fda904c287c2b19ce37195205e42b602879da84a/example/src/main/java/com/regula/facerecognition/webclient/Main.java)

**Comment by kishoreaoe** [comment]
thanks alot hleb,
